// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0HBSkCKr86V2pcQbqtdJAaAMot2QG9Y',
    appId: '1:854424120234:web:8c9a397270ebad7be999d3',
    messagingSenderId: '854424120234',
    projectId: 'soliman-cb8ff',
    authDomain: 'soliman-cb8ff.firebaseapp.com',
    storageBucket: 'soliman-cb8ff.firebasestorage.app',
    measurementId: 'G-Y3VN0HWQ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKm8MFmHQUQMV7z3NWjHhbRKOzauhqpfQ',
    appId: '1:854424120234:android:e300a02ff581feb7e999d3',
    messagingSenderId: '854424120234',
    projectId: 'soliman-cb8ff',
    storageBucket: 'soliman-cb8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBcwO2x49N0AoQqvSES2aXwYFdKN_u1QE',
    appId: '1:854424120234:ios:c31173672a543e14e999d3',
    messagingSenderId: '854424120234',
    projectId: 'soliman-cb8ff',
    storageBucket: 'soliman-cb8ff.firebasestorage.app',
    iosBundleId: 'com.example.plantCareUt',
  );
}
